# this is only to build this locally, to run the dependencies
# look at https://github.com/ruanbekker/rbkr-order-processing-system-microservices

services:
  order-service:
    build: .
    environment:
      - DATABASE_URL=postgres://user:pass@postgres:5432/orders?sslmode=disable
      - KAFKA_BROKERS=localhost:9092
      - PORT=8080
    ports:
      - "8080:8080"
    networks:
      - ops

networks:
  ops:
    name: ops

